@startuml

class Event{
  - String name;
  - String date;
  - long eventID;
  - Host host;
  - Location location;
}

class Host{
  - String name;
  - long ssn;
  - long hostID;
}

class Location{
  - long locationID;
  - String name;
  - String address;
  - long pricePerHour;
}

Host "1" -- "*" Event : hosts
Event "*" == "1" Location : has

@enduml
