@startuml
left to right direction
actor User as g

package Eventmanager {
  usecase "creates new Host" as UC1
  usecase "deletes Host" as UC2
  usecase "creates new Event" as UC3
  usecase "deletes Event" as UC4
}
g --> UC1
g --> UC2

g --> UC3
g --> UC4

@enduml